package org.genarator.models;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

@Getter
@Setter
@ToString
public class BitcoinParentBlockEdge implements Serializable {
    private String _key;
    // arango id of transaction 'btcTx/{_key}'
    private String _from;
    // arango id of block 'btcBlock/{_key}'
    private String _to;
    // arango _key is generated by arango
//    private String _key;
    public BitcoinParentBlockEdge(String key, String txId, String blockHeight) {
        this._key = key;
        this._from = txId;
        this._to = blockHeight;
    }
}
